server {
    listen 80;

    location /admin-dashboard {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /admin-dashboard/index.html;
    }

    location /api/ {
        proxy_pass http://admin-backend:8124; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}